# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project-structure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project-structure
  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseCrashlytics' 
  pod 'FirebasePerformance'

end
